on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SAARTEST }}
      run: |
        echo "$SUPER_SECRET"
